### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by frankrousseau** [django-nonrel/mongodb-engine#173]
Hello there,

It looks like installing mongodb-engine doesn't work anymore. Here are the repos I use:

```
git+https://github.com/django-nonrel/django@nonrel-1.3
git+https://github.com/django-nonrel/mongodb-engine@mongodb-engine-1.3
git+https://github.com/django-nonrel/djangotoolbox@toolbox-1.3
```

And here is the stack trace:

```
File "/var/lib/jenkins/jobs/website/workspace/virtualenv/lib/python2.6/site-packages/django/db/__init__.py", line 78, in <module>
connection = connections[DEFAULT_DB_ALIAS]
File "/var/lib/jenkins/jobswebsite/workspace/virtualenv/lib/python2.6/site-packages/django/db/utils.py", line 93, in __getitem__
backend = load_backend(db['ENGINE'])
File "/var/lib/jenkins/jobs/website/workspace/virtualenv/lib/python2.6/site-packages/django/db/utils.py", line 51, in load_backend
raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_mongodb_engine' isn't an available database backend. 
Try using django.db.backends.XXX, where XXX is one of:
     'dummy', 'mysql', 'oracle', 'postgresql', 'postgresql_psycopg2', 'sqlite3'
Error was: No module named utils
```

Do you know If I could do something to avoid that problem?

**Comment by ZuluPro** [comment]
Maybe this issue is still revelant: 
With Django 1.11
```
Traceback (most recent call last):
  File "./runtests.py", line 24, in <module>
    sys.exit(bool(main(sys.argv)))
  File "./runtests.py", line 19, in main
    result = test_runner.run_tests(["dbbackup.tests"])
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/test/utils.py", line 170, in setup_databases
    test_databases, mirrored_aliases = get_unique_databases_and_mirrors()
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/test/utils.py", line 272, in get_unique_databases_and_mirrors
    connection = connections[alias]
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/zulu/projects/django-dbbackup/.tox/py2.7-django1.10/local/lib/python2.7/site-packages/django/db/utils.py", line 134, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_mongodb_engine' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: No module named util
```
