### ISSUE TITLE
run manage.py test mytest fails

### ISSUE THREAD

**Issue by shuge** [django-nonrel/mongodb-engine#205]
My steps

```
python manage.py startproject mysite
python manage.py startapp mytest
```

update settings.py SITE_ID to '54d7805345afbc0239b56780'

```
create mytest/tests.py
```

mytest/tests.py

```
import httplib
from django.test import TestCase


class SimpleTest(TestCase):

    def test_it(self):
        self.assertEqual(httplib.OK, 200)
```

```
$ python manage.py test mytest --traceback
```

it will raises exception 
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/test/runner.py", line 145, in run_tests
    old_config = self.setup_databases()
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/test/runner.py", line 107, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/test/runner.py", line 279, in setup_databases
    verbosity, autoclobber=not interactive)
  File "/Users/lee/Downloads/mongodb-engine-master/django_mongodb_engine/creation.py", line 205, in create_test_db
    interactive=False, database=self.connection.alias)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 112, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/core/management/sql.py", line 216, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/contrib/sites/management.py", line 22, in create_default_site
    Site(pk=1, domain="example.com", name="example.com").save(using=db)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/base.py", line 547, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/base.py", line 575, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/base.py", line 670, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/base.py", line 706, in _do_insert
    using=using, raw=raw)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/djangotoolbox/db/basecompiler.py", line 587, in execute_sql
    value = self.ops.value_for_db(value, field)
  File "/Users/lee/sandbox/lib/python2.7/site-packages/djangotoolbox/db/base.py", line 245, in value_for_db
    field_kind, db_type, lookup)
  File "/Users/lee/Downloads/mongodb-engine-master/django_mongodb_engine/base.py", line 116, in _value_for_db
    raise DatabaseError(msg)
django.db.utils.DatabaseError: AutoField (default primary key) values must be strings representing an ObjectId on MongoDB (got u'1' instead). Please make sure your SITE_ID contains a valid ObjectId string.
```

**Comment by paulozullu** [comment]
Same here. Any solution?
