### ISSUE TITLE
TransactionManagementError when perform creation

### ISSUE THREAD

**Issue by buxx** [django-nonrel/mongodb-engine#219]
Trying to use `django-mongodb-engine` with fresh test project:

**testmongo/settings.py**

```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testmongo',
)

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_engine',
        'NAME': 'djtest',
    },
}
```

**testmongo/models.py**

```
from django.db import models

class Article(models.Model):
    name = models.CharField(max_length=32)
```

When try to save an article:

```
# python ./manage.py shell     
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from testmongo.models import Article
>>> Article.objects.create(name='a')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/bux/.virtualenvs/testmongo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bux/.virtualenvs/testmongo/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/bux/.virtualenvs/testmongo/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/bux/.virtualenvs/testmongo/local/lib/python2.7/site-packages/django/db/models/base.py", line 759, in save_base
    with transaction.atomic(using=using, savepoint=False):
  File "/home/bux/.virtualenvs/testmongo/local/lib/python2.7/site-packages/django/db/transaction.py", line 164, in __enter__
    "The outermost 'atomic' block cannot use "
TransactionManagementError: The outermost 'atomic' block cannot use savepoint = False when autocommit is off.
```

**requirmements.txt**:

```
Django==1.8.4
git+https://github.com/django-nonrel/django@nonrel-1.5
git+https://github.com/django-nonrel/djangotoolbox
git+https://github.com/django-nonrel/mongodb-engine
```

**pip freeze**

```
Django==1.8.4
argparse==1.2.1
django-mongodb-engine==0.6.0
djangotoolbox==1.8.0
pymongo==3.0.3
wsgiref==0.1.2
```

What's wrong ?

**Comment by markunsworth** [comment]
You shouldn't have `Django==1.8.4` in your requirements file as that will install the regular django.

You have the nonrel version of django in the next line which is the correct one to use.

**Comment by buxx** [comment]
Okay, thank's !
